disabled = false
languageCode = "es"
languageName = "Español"
weight = 1
title = "Ale."

[params]
displayName = "ES"
isoCode = "es"
rtl = false
dateFormat = "2 January 2006"
description = ""


[params.author]
image = "profile.jpg"
name = "Ale."
email = "aletec.contact@gmail.com"
headline = "Software Engineer y creador de contenido, desde España"
bio = "Soy un Software Engineer de 26 años viviendo en España y de vez en cuando me gusta divulgar y crear contenido, así que puedes encontrarme por YouTube, TikTok y por aquí mismo para ver un poco más de mí y mi forma de vivir la tecnología."
links = [
    { github = "https://github.com/alecron" },
    { tiktok = "https://tiktok.com/@elaletec" },
    { instagram = "https://instagram.com/aletecnstuff" },
    { linkedin = "https://linkedin.com/in/amagallon" },
    { x-twitter = "https://www.x.com/aletecnstuff" },
    { youtube = "https://www.youtube.com/@AleTecnstuff" }
]
