# netlify.toml

[build]
  command = """\
    git submodule update --init --recursive && \
    hugo --gc --minify
  """
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.23.2"
  TZ = "UTC"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.136.2"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.136.2"
